# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='cover'),
        ),
    ]
